request model
zjor/web-fetcher pull request #6
Opened 2023-11-05 19:07 UTC by sinkokri

2023-11-06 11:47 UTC, zjor requested changes

2023-11-06 11:47 UTC, zjor commented on src/main/java/com/github/zjor/webfetcher/client/Client.java
> +import com.github.zjor.webfetcher.dto.RequestDto;
Давай не использовать DTO, Dto - это уебищность корпоративной джавы
если посмотреть SDK любой уважающей конторы, там нет DTO, 
это все придумки Фаулера.
Если объект сериализуется в JSON и является DTO, то иногда я его называю JRequest

2023-11-06 11:47 UTC, zjor commented on src/main/java/com/github/zjor/webfetcher/notification/editor/Editor.java
>  public class Editor {
Давай переименуем этот класс во что-то более говорящее - зачем он?

2023-11-06 11:47 UTC, zjor commented on src/main/java/com/github/zjor/webfetcher/model/Request.java
> +  private UUID id;
тут будет работать автозаполнение?

2023-11-06 11:47 UTC, zjor commented on src/main/java/com/github/zjor/webfetcher/notification/publisher/EventManager.java
> +    public void notify(EventType eventType, RequestDto requestDto) {
этот метод не перекрывает ли Object.notify? для многопоточности?

2023-11-06 11:47 UTC, zjor commented on src/main/java/com/github/zjor/webfetcher/service/RequestService.java
> +public interface RequestService {
Давай уберем все интерфейсы, у которых только 1 реализация и не предвидится расширений?

2023-11-06 11:47 UTC, zjor commented on src/main/resources/db/migration/V1_1__Init_Schema.sql
filename --> to lower case

2023-11-07 20:13 UTC, sinkokri commented on src/main/java/com/github/zjor/webfetcher/notification/publisher/EventManager.java
> +    public void notify(EventType eventType, RequestDto requestDto) {
it didnt. removed anyway

2023-11-07 20:13 UTC, sinkokri commented on src/main/java/com/github/zjor/webfetcher/notification/editor/Editor.java
>  public class Editor {
removed for good

2023-11-07 20:14 UTC, sinkokri commented on src/main/java/com/github/zjor/webfetcher/model/Request.java
> +  private UUID id;
id was generated in the service. changed anyway to be generated by db

2023-11-07 20:15 UTC, sinkokri commented on src/main/resources/db/migration/V1_1__Init_Schema.sql
dont understand....

2023-11-07 21:17 UTC, merged